# Generated by Django 3.2.9 on 2022-03-08 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0005_auto_20220308_0321'),
        ('projectsapi', '0002_alter_project_projectm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userapi.projectmanagerprofile'),
        ),
    ]
