# Generated by Django 3.2.9 on 2022-03-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0007_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, default=1, max_length=1),
        ),
    ]
