# Generated by Django 3.2.9 on 2022-03-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0010_alter_project_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('user', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[(1, 'IN'), (2, 'OUT')], max_length=2)),
                ('amount', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapi.project')),
            ],
        ),
    ]
