# Generated by Django 3.2.9 on 2022-03-10 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0012_projectmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmaterial',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ProjectMaterialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[(1, 'IN'), (2, 'OUT')], max_length=2)),
                ('amount', models.CharField(max_length=200)),
                ('projectMaterial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapi.projectmaterial')),
            ],
        ),
    ]
