# Generated by Django 3.2.9 on 2022-03-10 11:12

from django.db import migrations, models
import django.db.models.deletion
import projectsapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0013_auto_20220310_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'InComplete'), (1, 'Complete')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapi.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('progress', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapi.projecttask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=projectsapi.models.imageDirectoryPath)),
                ('date', models.DateField(auto_now=True)),
                ('taskUpdate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapi.taskupdate')),
            ],
        ),
    ]
