# Generated by Django 3.2.9 on 2022-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0014_projecttask_taskphotos_taskupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[(0, 'InComplete'), (1, 'Complete')], max_length=2),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='progress',
            field=models.CharField(max_length=3),
        ),
    ]
