# Generated by Django 3.2.9 on 2022-03-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0016_chatmessage_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapi.project'),
        ),
    ]
