# Generated by Django 3.2.9 on 2022-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0018_alter_chatmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
