# Generated by Django 3.2.9 on 2022-03-12 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0020_alter_chatmessage_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chatRoom',
        ),
    ]
