# Generated by Django 3.2.9 on 2022-03-12 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0021_remove_chatmessage_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chatRoom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projectsapi.project'),
            preserve_default=False,
        ),
    ]
