# Generated by Django 3.2.9 on 2022-03-12 02:33

from django.db import migrations, models
import projectsapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0022_chatmessage_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='photo',
            field=models.ImageField(blank=True, upload_to=projectsapi.models.createChatPhoto),
        ),
    ]
