# Generated by Django 3.2.9 on 2022-03-23 05:48

from django.db import migrations, models
import django.db.models.deletion
import projectsapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0023_alter_chatmessage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='types',
            field=models.CharField(choices=[(0, 'Turn Key'), (1, 'Labour Rate')], default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=projectsapi.models.projectDirectoryPath)),
                ('currDate', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapi.project')),
            ],
        ),
    ]
