# Generated by Django 3.2.9 on 2022-03-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0024_auto_20220323_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocuments',
            name='filename',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
