# Generated by Django 3.2.9 on 2022-03-27 05:58

from django.db import migrations, models
import projectsapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0025_projectdocuments_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskphotos',
            name='photo',
            field=models.FileField(upload_to=projectsapi.models.imageDirectoryPath),
        ),
    ]
