# Generated by Django 3.2.9 on 2022-04-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0026_alter_taskphotos_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateField(auto_created=True)),
                ('fullname', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AttendaceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onDate', models.DateField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapi.labourtable')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapi.project')),
            ],
        ),
    ]
