# Generated by Django 3.2.9 on 2022-04-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0027_attendacetable_labourtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourtable',
            name='fullname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
