# Generated by Django 3.2.9 on 2022-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0028_alter_labourtable_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourtable',
            name='addedon',
            field=models.DateField(auto_now_add=True),
        ),
    ]
