# Generated by Django 3.2.9 on 2022-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0029_alter_labourtable_addedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacetable',
            name='onDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
