# Generated by Django 3.2.9 on 2022-04-18 04:43

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0030_alter_attendacetable_ondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendacetable',
            name='hours',
            field=models.CharField(blank=sqlalchemy.sql.expression.true, max_length=200),
        ),
    ]
