# Generated by Django 4.0.5 on 2022-06-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapi', '0031_attendacetable_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacetable',
            name='hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendacetable',
            name='onDate',
            field=models.DateField(),
        ),
    ]
