# Generated by Django 3.2.9 on 2022-03-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='types',
            new_name='type',
        ),
    ]
