# Generated by Django 3.2.9 on 2022-03-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_rename_types_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeProfile',
            new_name='ProjectManagerProfile',
        ),
    ]
