# Generated by Django 3.2.9 on 2022-03-07 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_rename_employeeprofile_projectmanagerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagerprofile',
            name='image',
            field=models.ImageField(upload_to=userapi.models.projectPath),
        ),
        migrations.CreateModel(
            name='SiteEngineerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=userapi.models.sitePath)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=userapi.models.inventoryPath)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=userapi.models.contractorPath)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=userapi.models.adminPath)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
