# Generated by Django 3.2.9 on 2022-03-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0005_auto_20220308_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='projectAss',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
