# Generated by Django 3.2.9 on 2022-03-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0007_notificationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='message',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
