# Generated by Django 3.2.9 on 2022-03-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0008_notificationtable_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtable',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
